// AUTO-GENERATED by scan-routes.mjs — 2026-06-15T10:26:24.347Z
// Re-run "node scan-routes.mjs" after adding/removing routes.
// Edit DEFAULT_*_PERMISSIONS below to customise each role's access.

// ==========================================
// 1. ALL AVAILABLE PERMISSIONS
// ==========================================

export const PERMISSIONS = {

  // ─── Admin: Admins (Admin/Sub-Admin management) ────────────────────────────
  ADMINS_LIST: 'GET:src/app/api/admin/admins',
  ADMINS_READ: 'GET:src/app/api/admin/admins/:userId',

  // ─── Admin: Business Registrations ────────────────────────────────────────
  // BUSINESS_REGISTRATIONS_READ: 'GET:src/app/api/admin/business-registrations/:id/',

  // ─── Admin: Listings ────────────────────────────────────────────────────────
  CREATE_CREATE: 'POST:src/app/api/admin/listings/create',
  IMPORT_CREATE_3: 'POST:src/app/api/admin/listings/import',
  LISTINGS_CREATE: 'POST:src/app/api/admin/listings',
  LISTINGS_DELETE: 'DELETE:src/app/api/admin/listings/:id',
  LISTINGS_LIST: 'GET:src/app/api/admin/listings',
  LISTINGS_READ: 'GET:src/app/api/admin/listings/:id',
  LISTING_READ_REPORT: "GET:src/app/api/admin/listings/:id/report",
  LISTINGS_UPDATE: 'PUT:src/app/api/admin/listings/:id',
  LISTINGS_UPDATE_1: 'PATCH:src/app/api/admin/listings/:id',

  // ─── Job bank ────────────────────────────────────────────────────────
  LISTING_CREATE: 'POST:src/app/api/admin/job-bank-requests/:id/listing',
  LISTING_CREATE_1: 'POST:src/app/api/job-bank-requests/:id/listing',
  JOB_BANK_REQUESTS_CREATE: 'POST:src/app/api/job-bank-requests',
  JOB_BANK_REQUESTS_DELETE: 'DELETE:src/app/api/admin/job-bank-requests',
  JOB_BANK_REQUESTS_DELETE_1: 'DELETE:src/app/api/admin/job-bank-requests/:id',
  JOB_BANK_REQUESTS_DELETE_2: 'DELETE:src/app/api/job-bank-requests/:id',
  JOB_BANK_REQUESTS_LIST: 'GET:src/app/api/admin/job-bank-requests',
  JOB_BANK_REQUESTS_LIST_1: 'GET:src/app/api/job-bank-requests',
  JOB_BANK_REQUESTS_READ: 'GET:src/app/api/admin/job-bank-requests/:id',
  JOB_BANK_REQUESTS_READ_1: 'GET:src/app/api/job-bank-requests/:id',
  JOB_BANK_REQUESTS_UPDATE: 'PUT:src/app/api/admin/job-bank-requests/:id',

  // ─── Admin: Metadata ────────────────────────────────────────────────────────
  BULK_CREATE_3: 'POST:src/app/api/admin/metadata/bulk',
  IMPORT_CREATE_4: 'POST:src/app/api/admin/metadata/import',
  METADATA_CREATE: 'POST:src/app/api/admin/metadata',
  METADATA_DELETE: 'DELETE:src/app/api/admin/metadata/:id',
  METADATA_LIST: 'GET:src/app/api/admin/metadata',
  METADATA_READ: 'GET:src/app/api/admin/metadata/:id',
  METADATA_UPDATE: 'PUT:src/app/api/admin/metadata/:id',

  // ─── Admin: Users ───────────────────────────────────────────────────────────
  BLOCK_UPDATE: 'PATCH:src/app/api/admin/users/:userId/block',
  PERMISSIONS_READ: 'GET:src/app/api/admin/users/:userId/permissions',
  PERMISSIONS_UPDATE: 'PUT:src/app/api/admin/users/:userId/permissions',
  USERS_LIST: 'GET:src/app/api/admin/users',
  USERS_READ: 'GET:src/app/api/admin/users/:userId',

  // ─── Auth (MFA, Signup, Verify, Password) ───────────────────────────────────
  CHANGE_PASSWORD_CREATE: 'POST:src/app/api/auth/change-password',
  CHANGE_PASSWORD_CREATE_1: 'POST:src/app/api/auth/forgot-password/change-password',
  SEND_OTP_CREATE: 'POST:src/app/api/auth/forgot-password/send-otp',
  SEND_OTP_CREATE_1: 'POST:src/app/api/auth/send-otp',
  SETUP_CREATE: 'POST:src/app/api/auth/mfa/setup',
  SIGNUP_CREATE: 'POST:src/app/api/auth/signup',
  VERIFY_CREATE: 'POST:src/app/api/auth/mfa/verify',
  VERIFY_EMAIL_LIST: 'GET:src/app/api/auth/verify-email',
  VERIFY_OTP_CREATE: 'POST:src/app/api/auth/forgot-password/verify-otp',
  VERIFY_OTP_CREATE_1: 'POST:src/app/api/auth/verify-otp',

  // ─── Blog ───────────────────────────────────────────────────────────────────
  BLOG_CREATE: 'POST:src/app/api/blog',
  BLOG_DELETE: 'DELETE:src/app/api/blog',
  BLOG_DELETE_1: 'DELETE:src/app/api/blog/:id',
  BLOG_EXPIRE_CREATE: 'POST:src/app/api/qstash/blog-expire',
  BLOG_LIST: 'GET:src/app/api/blog',
  BLOG_PUBLISH_CREATE: 'POST:src/app/api/qstash/blog-publish',
  BLOG_UPDATE: 'PUT:src/app/api/blog/:id',
  IMPORT_CREATE_7: 'POST:src/app/api/blog/import',

  // ─── Subscribers / Broadcast ─────────────────────────────────────────────────
  BROADCAST_CREATE: 'POST:src/app/api/admin/subscribers/broadcast',
  BULK_IMPORT_CREATE: 'POST:src/app/api/admin/subscribers/bulk-import',
  EXPORT_LIST: 'GET:src/app/api/admin/subscribers/export',
  STATS_LIST: 'GET:src/app/api/admin/subscribers/stats',
  SUBSCRIBE_CREATE: 'POST:src/app/api/subscribe',
  SUBSCRIBERS_DELETE: 'DELETE:src/app/api/admin/subscribers/:id',
  SUBSCRIBERS_LIST: 'GET:src/app/api/admin/subscribers',
  SUBSCRIBERS_READ: 'GET:src/app/api/admin/subscribers/:id',
  SUBSCRIBERS_UPDATE: 'PATCH:src/app/api/admin/subscribers/:id',
  UNSUBSCRIBE_LIST: 'GET:src/app/api/subscribe/unsubscribe',

  // ─── Contact ───────────────────────────────────────────────────────────────
  CONTACT_CREATE: 'POST:src/app/api/contact',
  CONTACT_LIST: 'GET:src/app/api/contact',
  CONTACT_READ: 'GET:src/app/api/contact/:id',
  CONTACT_UPDATE: 'PATCH:src/app/api/contact/:id',
  REPLY_CREATE: 'POST:src/app/api/contact/:id/reply',

  // ─── FAQ ────────────────────────────────────────────────────────────────────
  FAQ_CREATE: 'POST:src/app/api/faq',
  FAQ_DELETE: 'DELETE:src/app/api/faq/:id',
  FAQ_LIST: 'GET:src/app/api/faq',
  FAQ_READ: 'GET:src/app/api/faq/:id',
  FAQ_UPDATE: 'PUT:src/app/api/faq/:id',

  // ─── Listings (Public & User) ───────────────────────────────────────────────
  FILTERS_LIST: 'GET:src/app/api/listings/filters',
  IMPORT_CREATE_8: 'POST:src/app/api/listings/import',
  LISTINGS_LIST_1: 'GET:src/app/api/listings',
  MY_LIST: 'GET:src/app/api/listings/my',
  SUBMIT_CREATE: 'POST:src/app/api/listings/submit',
  TOGGLE_LISTINGS: "PATCH:src/app/api/listings/:id/toggle",
  UPDATE_REQUEST_UPDATE_2: 'PUT:src/app/api/listings/update-request',

  // ─── Services ───────────────────────────────────────────────────────────────
  SERVICES_CREATE: 'POST:src/app/api/admin/services',
  SERVICES_DELETE: 'DELETE:src/app/api/admin/services',
  SERVICES_DELETE_1: 'DELETE:src/app/api/admin/services/:id',
  SERVICES_LIST: 'GET:src/app/api/admin/services',
  SERVICES_LIST_1: 'GET:src/app/api/services',
  SERVICES_READ: 'GET:src/app/api/admin/services/:id',
  SERVICES_UPDATE: 'PUT:src/app/api/admin/services/:id',
  IMPORT_CREATE_5: 'POST:src/app/api/admin/services/import',

  // ─── SiteConfig ───────────────────────────────────────────────────────────────
  SITECONFIG_CREATE: 'POST:src/app/api/siteConfig',
  SITECONFIG_DELETE: 'DELETE:src/app/api/siteConfig/:id',
  SITECONFIG_LIST: 'GET:src/app/api/siteConfig',
  SITECONFIG_UPDATE: 'PUT:src/app/api/siteConfig/:id',

  // ─── Testimonials ─────────────────────────────────────────────────────────────
  TESTIMONIALS_CREATE: 'POST:src/app/api/testimonials',
  TESTIMONIALS_DELETE: 'DELETE:src/app/api/testimonials/:id',
  TESTIMONIALS_LIST: 'GET:src/app/api/testimonials',
  TESTIMONIALS_UPDATE: 'PUT:src/app/api/testimonials/:id',

  // ─── User Profile ─────────────────────────────────────────────────────────────
  COMPLETE_PROFILE_CREATE: 'POST:src/app/api/user/complete-profile',
  HISTORY_LIST: 'GET:src/app/api/user/history',
  PROFILE_LIST: 'GET:src/app/api/user/profile',
  PROFILE_UPDATE: 'PATCH:src/app/api/user/profile',
  USER_LIST_2: 'GET:src/app/api/user',

  // ─── QStash / Revalidate ───────────────────────────────────────────────────────
  EXPIRE_CREATE: 'POST:src/app/api/qstash/expire',
  PUBLISH_CREATE: 'POST:src/app/api/qstash/publish',
  REVALIDATE_CREATE: 'POST:src/app/api/revalidate',
  REVALIDATE_LIST: 'GET:src/app/api/revalidate',

  // job-appliactions
  JOB_APPLICATIONS_DELETE: 'DELETE:src/app/api/admin/job-applications/:id',
  JOB_APPLICATIONS_LIST: 'GET:src/app/api/admin/job-applications',
  JOB_APPLICATIONS_UPDATE: 'PATCH:src/app/api/admin/job-applications/:id',

  // ─── Subscription Plans ───────────────────────────────────────────────────
  PLANS_LIST: 'GET:src/app/api/admin/plans',
  PLANS_CREATE: 'POST:src/app/api/admin/plans',
  PLANS_UPDATE: 'PUT:src/app/api/admin/plans/:id',
  PLANS_DELETE: 'DELETE:src/app/api/admin/plans/:id',
  BILLING_CHECKOUT_CREATE: 'POST:src/app/api/billing/checkout',
  BILLING_PORTAL_CREATE: 'POST:src/app/api/billing/portal',

  USER_PLANS_LIST: "GET:src/app/api/plans",

  SUBSCRIPTION_USAGE: "GET:src/app/api/subscription/usage",
  BILLING_HISTORY: "GET:src/app/api/billing/history",

  BILLING_CHECKOUT_LOGS: "GET:src/app/api/billing/checkout-redirect-log",
  BILLING_CANCEL: 'POST:src/app/api/billing/cancel',

  SWITCH_PLANS: "POST:src/app/api/billing/switch",
  RESUME_BILLING: "POST:src/app/api/billing/resume",

  SUBSCRIBE_ME: "GET:src/app/api/subscription/me",

  BILLING_ACCOUNT: "GET:src/app/api/billing/account",

  PENDING_BILLS: "GET:src/app/api/billing/outstanding",

  SUBSCRIPTION_USAGE_HISTORY: "GET:src/app/api/subscription/usage-history",

  CREADITS_LIST: "GET:src/app/api/admin/credit-bundles",

  CREADITS_PUT: "PUT:src/app/api/admin/credit-bundles/:id",

  CREADITS_DELETE: "DELETE:src/app/api/admin/credit-bundles/:id",

  CREADITS_SETTINGS_PUT: "PUT:src/app/api/admin/credit-settings",

  CREADITS_SETTINGS_GET: "GET:src/app/api/admin/credit-settings",

  CREADITS_CREAT: "POST:src/app/api/admin/credit-bundles",

  ADMIN_CREADITS_AUDIT_LOGS: "GET:src/app/api/admin/audit-logs",

  EMPLOYER_CREADITS_BUNDLES: "GET:src/app/api/employer/credit-bundles",
  EMPLOYER_CREADITS_ACTIVITY: "GET:src/app/api/employer/credits/activity",
  EMPLOYER_CREADITS_CHECKOUT: "POST:src/app/api/employer/credits/checkout",
  EMPLOYER_CREADITS_WALLET: "GET:src/app/api/employer/credits/wallet",

  ADMIN_CREDITS_GET: "GET:src/app/api/admin/credits",
  ADMIN_CREDITS_USER: "GET:src/app/api/admin/credits/:id",

  ADMIN_CREDITS_ADJUST_CREAT: "POST:src/app/api/admin/credits/:id/adjust",
  ADMIN_CREDITS_TRANSACTION: "GET:src/app/api/admin/credits/:userId/transactions",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// ==========================================
// 2. PUBLIC PERMISSION PATTERNS
// ==========================================
// These routes require NO authentication. Format: "METHOD:src/app/api/path"
// Supports wildcards: :id (single segment), :path* (multi-segment)

export const PUBLIC_PERMISSION_PATTERNS: string[] = [

  'POST:src/app/api/job-apply',

  'POST:src/app/api/job-bank-requests',

  'POST:src/app/api/subscribe',
  'GET:src/app/api/subscribe/unsubscribe',

  'POST:src/app/api/auth/forgot-password/send-otp',
  'POST:src/app/api/auth/forgot-password/verify-otp',

  'POST:src/app/api/revalidate',
  'GET:src/app/api/revalidate',

  // ─── Auth Routes (always public - needed for login/signup flow) ───────────────
  'GET:src/app/api/auth/:path*',
  'POST:src/app/api/auth/:path*',
  'PATCH:src/app/api/auth/:path*',
  'PUT:src/app/api/auth/:path*',
  'DELETE:src/app/api/auth/:path*',

  // ─── Public Content: Blog (read-only) ─────────────────────────────────────────
  'GET:src/app/api/blog',
  'GET:src/app/api/blog/:id',

  // ─── Public Content: FAQ (read-only) ──────────────────────────────────────────
  'GET:src/app/api/faq',
  'GET:src/app/api/faq/:id',

  // ─── Public Content: Services (read-only) ─────────────────────────────────────
  'GET:src/app/api/services',

  // ─── Public Content: Testimonials (read-only) ───────────────────────────────────
  'GET:src/app/api/testimonials',
  'GET:src/app/api/testimonials/:id',

  // ─── Public Listings (browsing - no auth required) ─────────────────────────────
  'GET:src/app/api/listings',
  'GET:src/app/api/listings/:id',
  'GET:src/app/api/listings/filters',

  // ─── Public Submissions ─────────────────────────────────────────────────────
  'POST:src/app/api/contact',
  'GET:src/app/api/admin/metadata',

  // ─── SiteConfig (public read) ──────────────────────────────────────────────────
  'GET:src/app/api/siteConfig',

  'POST:src/app/api/webhooks/stripe',
  "GET:src/app/api/admin/audit-logs",
];

// ==========================================
// 3. DEFAULT ROLE PERMISSIONS
// ==========================================

export const DEFAULT_USER_PERMISSIONS: Permission[] = [
  // Public content (read-only)
  PERMISSIONS.BLOG_LIST,
  PERMISSIONS.FAQ_LIST,
  PERMISSIONS.FAQ_READ,
  PERMISSIONS.SERVICES_LIST_1,
  PERMISSIONS.TESTIMONIALS_LIST,
  PERMISSIONS.SITECONFIG_LIST,

  PERMISSIONS.LISTING_READ_REPORT,

  // Public listings
  PERMISSIONS.LISTINGS_LIST_1,
  PERMISSIONS.FILTERS_LIST,

  PERMISSIONS.SUBMIT_CREATE,
  PERMISSIONS.UPDATE_REQUEST_UPDATE_2,
  PERMISSIONS.TOGGLE_LISTINGS,

  // User's own data
  PERMISSIONS.MY_LIST,
  PERMISSIONS.PROFILE_LIST,
  PERMISSIONS.HISTORY_LIST,
  PERMISSIONS.USER_LIST_2,
  // Job bank (own)
  PERMISSIONS.JOB_BANK_REQUESTS_LIST_1,
  PERMISSIONS.JOB_BANK_REQUESTS_READ_1,
  // Contact (own)
  PERMISSIONS.CONTACT_LIST,
  PERMISSIONS.CONTACT_READ,
  // Auth verified email check
  PERMISSIONS.VERIFY_EMAIL_LIST,
  // Misc
  PERMISSIONS.UNSUBSCRIBE_LIST,
  PERMISSIONS.REVALIDATE_LIST,
  PERMISSIONS.PLANS_LIST,
  PERMISSIONS.BILLING_CHECKOUT_CREATE,
  PERMISSIONS.BILLING_PORTAL_CREATE,
  PERMISSIONS.USER_PLANS_LIST,
  PERMISSIONS.SUBSCRIPTION_USAGE,
  PERMISSIONS.BILLING_HISTORY,
  PERMISSIONS.BILLING_CHECKOUT_LOGS,
  PERMISSIONS.BILLING_CANCEL,
  PERMISSIONS.SWITCH_PLANS,
  PERMISSIONS.RESUME_BILLING,
  PERMISSIONS.SUBSCRIBE_ME,
  PERMISSIONS.BILLING_ACCOUNT,
  PERMISSIONS.PENDING_BILLS,
  PERMISSIONS.SUBSCRIPTION_USAGE_HISTORY,

  PERMISSIONS.EMPLOYER_CREADITS_BUNDLES,
  PERMISSIONS.EMPLOYER_CREADITS_ACTIVITY,
  PERMISSIONS.EMPLOYER_CREADITS_CHECKOUT,
  PERMISSIONS.EMPLOYER_CREADITS_WALLET,

  PERMISSIONS.ADMIN_CREDITS_GET,
  PERMISSIONS.ADMIN_CREDITS_USER,

  PERMISSIONS.ADMIN_CREDITS_ADJUST_CREAT,
  PERMISSIONS.ADMIN_CREDITS_TRANSACTION

];

export const DEFAULT_SUB_ADMIN_PERMISSIONS: Permission[] = [
  ...DEFAULT_USER_PERMISSIONS,

  // Admin panel access (users)
  PERMISSIONS.USERS_LIST,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.BLOCK_UPDATE,

  // Removed: ADMINS_LIST, ADMINS_READ   → cannot see/administer admins
  // Removed: PERMISSIONS_READ, PERMISSIONS_UPDATE → cannot manage permissions

  // Business registrations (view)
  // PERMISSIONS.BUSINESS_REGISTRATIONS_READ,

  // Listings management
  PERMISSIONS.LISTINGS_LIST,
  PERMISSIONS.LISTINGS_READ,
  PERMISSIONS.TOGGLE_LISTINGS,

  // Metadata view
  PERMISSIONS.METADATA_LIST,
  PERMISSIONS.METADATA_READ,

  // Contact management
  PERMISSIONS.CONTACT_UPDATE,
  PERMISSIONS.REPLY_CREATE,

  PERMISSIONS.PLANS_LIST,
  PERMISSIONS.PLANS_CREATE,
  PERMISSIONS.PLANS_UPDATE,
  PERMISSIONS.PLANS_DELETE,
  PERMISSIONS.BILLING_PORTAL_CREATE,
  PERMISSIONS.PENDING_BILLS,
  PERMISSIONS.SUBSCRIPTION_USAGE_HISTORY,


  PERMISSIONS.CREADITS_LIST,

  PERMISSIONS.CREADITS_PUT,

  PERMISSIONS.CREADITS_DELETE,

  PERMISSIONS.CREADITS_SETTINGS_PUT,

  PERMISSIONS.CREADITS_SETTINGS_GET,

  PERMISSIONS.CREADITS_CREAT,

];

export const DEFAULT_ADMIN_PERMISSIONS: Permission[] = [
  ...Object.values(PERMISSIONS) as Permission[],
];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, Permission[]> = {
  'user': DEFAULT_USER_PERMISSIONS,
  'sub-admin': DEFAULT_SUB_ADMIN_PERMISSIONS,
  'admin': DEFAULT_ADMIN_PERMISSIONS,
};

// ==========================================
// 4. HELPERS
// ==========================================

/**
 * Check if a concrete permission key matches a pattern (handles :id wildcards)
 */
function matchesPermissionPattern(pattern: string, concreteKey: string): boolean {
  // Step 1: Replace :path* with a safe placeholder (no regex special chars)
  let regexPattern = pattern.replace(/:path\*/g, '__PATH_STAR__');

  // Step 2: Escape regex special characters (curly braces, dots, etc.)
  regexPattern = regexPattern.replace(/[.+^${}()|[\]\\]/g, '\\$&');

  // Step 3: Now safely replace the placeholder with .*
  regexPattern = regexPattern.replace(/__PATH_STAR__/g, '.*');

  // Step 4: Handle single-segment parameters
  regexPattern = regexPattern
    .replace(/:agreementId/g, '[^/]+')
    .replace(/:listingId/g, '[^/]+')
    .replace(/:userId/g, '[^/]+')
    .replace(/:token/g, '[^/]+')
    .replace(/:id/g, '[^/]+')
    .replace(/:path/g, '[^/]+');

  try {
    return new RegExp(`^${regexPattern}$`).test(concreteKey);
  } catch (e) {
    console.error('[Middleware] Regex error for pattern:', pattern, e);
    return pattern === concreteKey;
  }
}

/**
 * Check if a concrete permission key is in the public list
 */
export function isPublicRoute(concreteKey: string): boolean {
  return PUBLIC_PERMISSION_PATTERNS.some(pattern =>
    matchesPermissionPattern(pattern, concreteKey)
  );
}