#!/usr/bin/env node
/**
 * scan-routes.mjs
 * Run: node scan-routes.mjs [app-dir] [output-path]
 *
 * Scans your Next.js App Router for all route.ts files,
 * extracts exported HTTP methods, and generates a permissions.ts file.
 *
 * Defaults:cd 
 *   app-dir   = ./app
 *   output    = ./lib/permissions.ts
 */

import fs   from 'fs';
import path from 'path';

const APP_DIR    = process.argv[2] ?? './src/app';
const OUTPUT     = process.argv[3] ?? './src/lib/permissions.ts';
const HTTP_METHODS = ['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'];

// ─── 1. Walk filesystem ───────────────────────────────────────────────────────

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      // skip node_modules, .next, hidden dirs
      if (!entry.name.startsWith('.') && entry.name !== 'node_modules' && entry.name !== '.next') {
        walk(full, files);
      }
    } else if (entry.name === 'route.ts' || entry.name === 'route.js') {
      files.push(full);
    }
  }
  return files;
}

// ─── 2. Extract exported HTTP methods from a file ────────────────────────────

function extractMethods(filePath) {
  const src = fs.readFileSync(filePath, 'utf8');
  const found = [];
  for (const method of HTTP_METHODS) {
    // matches: export async function GET / export function GET / export const GET
    const re = new RegExp(
      `export\\s+(?:async\\s+)?(?:function\\s+${method}|const\\s+${method}\\s*=)`,
      'm'
    );
    if (re.test(src)) found.push(method);
  }
  return found;
}

// ─── 3. Convert file path → API route path ───────────────────────────────────
//   ./app/api/users/[id]/route.ts  →  /api/users/:id

function toApiPath(filePath) {
  let p = filePath
    .replace(/\\/g, '/')                 // windows → posix
    .replace(/^\.\/app/, '')             // strip leading ./app
    .replace(/\/route\.(ts|js)$/, '')    // strip /route.ts
    .replace(/\(.*?\)\//g, '')           // strip route groups like (auth)/
    .replace(/\[\.\.\.([^\]]+)\]/g, '*') // [...slug] → *
    .replace(/\[([^\]]+)\]/g, ':$1');    // [id] → :id

  return p || '/';
}

// ─── 4. Build permission key name from method + path ─────────────────────────
//   GET /api/users/:id  →  USER_READ

function toPermKey(method, apiPath) {
  const segments = apiPath.split('/').filter(Boolean); // ['api','users',':id']

  // strip leading 'api' segment
  const parts = segments[0] === 'api' ? segments.slice(1) : segments;

  // take the last non-param, non-admin segment as the resource name
  const resource = [...parts]
    .filter(p => !p.startsWith(':') && p !== '*' && p !== 'admin')
    .pop() ?? 'resource';

  // action from method
  const action = {
    GET:    parts.some(p => p.startsWith(':') || p === '*') ? 'READ'   : 'LIST',
    POST:   'CREATE',
    PUT:    'UPDATE',
    PATCH:  'UPDATE',
    DELETE: 'DELETE',
    HEAD:   'HEAD',
    OPTIONS:'OPTIONS',
  }[method] ?? method;

  return `${resource.toUpperCase().replace(/-/g, '_')}_${action}`;
}

// ─── 5. Main ─────────────────────────────────────────────────────────────────

const routeFiles = walk(APP_DIR);

if (routeFiles.length === 0) {
  console.error(`No route.ts files found under "${APP_DIR}". Check your app directory path.`);
  process.exit(1);
}

const routes = [];           // { method, apiPath, permKey }
const keyCount = {};         // dedup keys

for (const file of routeFiles) {
  const methods = extractMethods(file);
  const apiPath = toApiPath(file);

  for (const method of methods) {
    let key = toPermKey(method, apiPath);

    // deduplicate: if key already used, append a counter
    if (keyCount[key] !== undefined) {
      keyCount[key]++;
      key = `${key}_${keyCount[key]}`;
    } else {
      keyCount[key] = 0;
    }

    routes.push({ method, apiPath, permKey: key, file });
  }
}

// Sort: group by resource
routes.sort((a, b) => a.permKey.localeCompare(b.permKey));

// ─── 6. Generate permissions.ts ──────────────────────────────────────────────

const permissionsBlock = routes
  .map(r => `  ${r.permKey.padEnd(30)}: '${r.method}:${r.apiPath}',`)
  .join('\n');

// Default user gets safe read-only GET permissions that don't touch admin
const defaultUserPerms = routes
  .filter(r => r.method === 'GET' && !r.apiPath.includes('/admin'))
  .map(r => `  PERMISSIONS.${r.permKey},`)
  .join('\n');

// Admin gets everything
const allPerms = routes
  .map(r => `  PERMISSIONS.${r.permKey},`)
  .join('\n');

const output = `// AUTO-GENERATED by scan-routes.mjs — ${new Date().toISOString()}
// Re-run "node scan-routes.mjs" after adding/removing routes.
// Edit DEFAULT_*_PERMISSIONS below to customise each role's access.

// ─── All available permissions ───────────────────────────────────────────────

export const PERMISSIONS = {
${permissionsBlock}
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// ─── Default permission sets per role ────────────────────────────────────────
// Adjust these lists to control what each role can do out of the box.

export const DEFAULT_USER_PERMISSIONS: Permission[] = [
${defaultUserPerms || '  // no safe GET routes found — add them here'}
];

export const DEFAULT_SUB_ADMIN_PERMISSIONS: Permission[] = [
  ...DEFAULT_USER_PERMISSIONS,
  // add extra sub-admin permissions here, e.g.:
  // PERMISSIONS.USER_LIST,
  // PERMISSIONS.POST_CREATE,
];

export const DEFAULT_ADMIN_PERMISSIONS: Permission[] = [
  ...Object.values(PERMISSIONS) as Permission[],
];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, Permission[]> = {
  'user':      DEFAULT_USER_PERMISSIONS,
  'sub-admin': DEFAULT_SUB_ADMIN_PERMISSIONS,
  'admin':     DEFAULT_ADMIN_PERMISSIONS,
};
`;

// ─── 7. Write output ─────────────────────────────────────────────────────────

const outDir = path.dirname(OUTPUT);
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(OUTPUT, output, 'utf8');

// ─── 8. Print summary table ──────────────────────────────────────────────────

const METHOD_COLOR = {
  GET:    '\x1b[32m',   // green
  POST:   '\x1b[34m',   // blue
  PUT:    '\x1b[33m',   // yellow
  PATCH:  '\x1b[33m',   // yellow
  DELETE: '\x1b[31m',   // red
};
const RESET = '\x1b[0m';
const DIM   = '\x1b[2m';

console.log(`\n  Scanned: ${APP_DIR}`);
console.log(`  Output:  ${OUTPUT}\n`);
console.log(`  ${'METHOD'.padEnd(8)} ${'API PATH'.padEnd(40)} PERMISSION KEY`);
console.log(`  ${'-'.repeat(80)}`);

for (const r of routes) {
  const col = METHOD_COLOR[r.method] ?? '';
  console.log(
    `  ${col}${r.method.padEnd(8)}${RESET}` +
    `${DIM}${r.apiPath.padEnd(40)}${RESET}` +
    r.permKey
  );
}

console.log(`\n  ${routes.length} permission(s) found across ${routeFiles.length} route file(s).\n`);
